
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Update these values with your new Supabase project credentials
const SUPABASE_URL = ""; // Add your new Supabase URL here
const SUPABASE_PUBLISHABLE_KEY = ""; // Add your new Supabase anon/public key here

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
