// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdxucidzsjqwzdgcyqfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkeHVjaWR6c2pxd3pkZ2N5cWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTQzNTUsImV4cCI6MjA2MjM5MDM1NX0.fPPi1lt0DRrDdT-fMWEKkz2MzzXyougWpcTJpzeDcbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);